### PR TITLE
Don't use type variables in patterns

### PR DESCRIPTION
**Pull request by goldfirere**
This PR is an attempt to fix part #13 (getting GHC 8.10.7 compatibility). But it doesn't work, because of an overlapping instance. The sad thing is that I think there really is an overlapping instance. I will report a GHC bug about this shortly.

### CODE REVIEW

**Comment by goldfirere** [comment]
The GHC bug is [reported upstream](https://gitlab.haskell.org/ghc/ghc/-/issues/21208). But we should still arrange not to have overlapping instances here.

**Comment by Mikolaj** [comment]
Thanks a lot. Apologies for the conflict. Could you rebase and resolve the conflict so that CI tries out 8.10.7 and 9.0.2? Thank you.

**Comment by Mikolaj** [comment]
Thank you. Now CI shows the overlap: https://github.com/Mikolaj/horde-ad/runs/5516892917?check_suite_focus=true#step:18:29

I don't understand much from this error message, though.

**Comment by Mikolaj** [comment]
Might this be related to `AllowAmbiguousTypes` that was IIRC needed to define this `SliceS` constructor?

**Comment by Mikolaj** [comment]
@goldfirere: while I'm clueless about the overlapping instances (all I know the class is defined here: https://hackage.haskell.org/package/orthotope-0.1.2.0/docs/Data-Array-Internal-Shape.html#t:Shape), I think the actual errors in 9.2.2 are due to a missing argument to `From2S` and so probably unrelated: https://github.com/Mikolaj/horde-ad/runs/5516892563?check_suite_focus=true#step:18:37

Do I get it right. Would it compile fine in GHC 9.2.2 once fixed? (And would the older GHCs compile fine with `IncoherentInstances`?)

How could we get rid of the overlapping instances?

**Comment by Mikolaj** [comment]
Another, probably related, problem with SliceS: https://github.com/Mikolaj/horde-ad/blob/01f5b467d1b0ccf9e8e4244e0837829f857a6807/src/HordeAd/Core/HasDual.hs#L191

Uncommenting the type signature doesn't help:

```
src/HordeAd/Core/HasDual.hs:188:14: error:
    • Couldn't match type: (i0 + n) + k0
                     with: (i + n) + k
      Expected: Dual (OS.Array (((i + n) + k) : rest) Double)
                -> Dual (OS.Array (n : rest) Double)
        Actual: Dual (OS.Array (((i0 + n) + k0) : rest) Double)
                -> Dual (OS.Array (n : rest) Double)
      NB: ‘+’ is a non-injective type family
      The type variables ‘i0’, ‘k0’ are ambiguous
    • When checking that instance signature for ‘dSliceS’
        is more general than its signature in the class
        Instance sig: forall (i :: GHC.TypeNats.Nat)
                             (n :: GHC.TypeNats.Nat) (k :: GHC.TypeNats.Nat)
                             (rest :: [GHC.TypeNats.Nat]).
                      (KnownNat i, KnownNat n, KnownNat k, OS.Shape rest) =>
                      Dual (OS.Array (((i + n) + k) : rest) Double)
                      -> Dual (OS.Array (n : rest) Double)
           Class sig: forall (i :: GHC.TypeNats.Nat)
                             (n :: GHC.TypeNats.Nat) (k :: GHC.TypeNats.Nat)
                             (rest :: [GHC.TypeNats.Nat]).
                      (KnownNat i, KnownNat n, KnownNat k, OS.Shape rest) =>
                      Dual (OS.Array (((i + n) + k) : rest) Double)
                      -> Dual (OS.Array (n : rest) Double)
      In the instance declaration for ‘HasRanks Double’
    |
188 |   dSliceS :: forall i n k rest.
```

**Comment by Mikolaj** [comment]
The `dSliceS` error from above is now reproducible on master branch (apologies for the merge conflicts again --- everything is now overhauled according to your ideas from last meeting --- the main class takes the dual component type as argument (e.g., Delta0 Double), not the primal (e.g., Double));

https://github.com/Mikolaj/horde-ad/blob/d069a45773ed849913b5ebd0345153072f304fd9/src/HordeAd/Core/DualClass.hs#L234-L238

Even the `dSliceS` signature alone suffices to cause an error. I wonder if the problem is going to vanish with the 9.0.2-compatible reformulation.

**Comment by Mikolaj** [comment]
@goldfirere: I'm now blocked by this, because performance with GHC 9.2.2 is degraded and requires random hacks and with HEAD even more so (https://github.com/Mikolaj/horde-ad/issues/14), which makes performance measurements with GHC >= 9.2 suspect. Consequently, whenever I change anything in the code, I can't confidently benchmark the effects not having access to 9.0.2 at least. And I experienced with this codebase it's easy to gradually lose performance from little changes, feature additions or from optimizations that magnify unrelated pre-existing performance problems. If you are busy, I'd rebase and merge and try to complete this myself. I'm going to yell for help again, if I fail.

**Comment by Mikolaj** [comment]
The rebase is going to be hopeless, so let me copy over the relevant bits and try to make it work.

**Comment by Mikolaj** [comment]
I have manually rebased and completed this PR's work: d68277fb6b94907dfa8a7c5bebf0902f181f42a9 d68277fb6b94907dfa8a7c5bebf0902f181f42a9 cf6eaf7d392289bb7ebb14262a9c2e4439ee71b7

@goldfirere: That's so close to what you've proposed, including the IncoherentInstances under CPP that I'm not even asking for your review before closing. You may still have a chance to look at this code if you attempt to eliminate the auxiliary function that are needed only to capture proper types (I think the current proxies are not enough to fix that, but perhaps more proxies would be?) or to generally overhaul this type-level code if it's somehow fundamentally flawed.

Closing. Thank you!
